apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: kube-public  # This makes it accessible across clusters
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

