kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.220.0.0/16"
  serviceSubnet: "10.225.0.0/16"
nodes:
- role: control-plane
  labels:
    az: a
- role: worker
  labels:
    az: a
- role: worker
  labels:
    az: b
- role: worker
  labels:
    az: c
